-- Modules
require 'user.plugins'
require 'user.impatient'
require 'user.opts'
require 'user.keys'
require 'user.pluginopts'
require 'user.completion'
require 'user.lsp'
require 'user.telescope'
require 'user.treesitter'
require 'user.autopairs'
require 'user.comment'
require 'user.git'
require 'user.explorer'
require 'user.bufferline'
require 'user.statusline'
require 'user.project'
require 'user.indentline'
require 'user.greeter'

vim.cmd 'source ~/.config/nvim/vim/firenvim.vim'
