; bug.n - tiling window management
; @version 9.0.2

Config_showBar=1
Config_horizontalBarPos=38
; Config_horizontalBarPos=4
Config_verticalBarPos=tray
Config_barWidth=300
Config_singleRowBar=1
Config_spaciousBar=1

Config_fontName=Lato Bold
Config_fontSize=10
Config_largeFontSize=24
; Config_color_#1-3=view;layout;title;shebang;time;date;"any text";battery;volume
Config_backColor_#1=Black;Black;Black;Black;Black;Black;Black;Black;Black
Config_backColor_#2=Black;Black;Black;Black;Black;Black;Black;Black;Black
Config_backColor_#3=Black;Black;Black;Black;Black;Black;Black;Black;Black
Config_foreColor_#1=Black;Black;Black;Black;Black;Black;Black;Black;Black
Config_foreColor_#2=Black;Black;Black;Black;Black;Black;Black;Black;Black
Config_foreColor_#3=Black;Black;Black;Black;Black;Black;Black;Black;Black
Config_fontColor_#1=6F7579;D5D5D5;;;;;;;
Config_fontColor_#2=D5D5D5;D5D5D5;;;;;;;
Config_fontColor_#3=D5D5D5;D5D5D5;;;;;;;
Config_barTransparency=off
Config_barCommands=Run, explore doc;Monitor_toggleBar();Main_reload();Reload;ExitApp
Config_readinBat=0
Config_readinCpu=0
Config_readinDate=0
Config_readinDateFormat=dd MMM yyyy
Config_readinDiskLoad=0
Config_readinMemoryUsage=0
Config_readinNetworkLoad=0
Config_readinTime=0
Config_readinTimeFormat=HH:mm
Config_readinVolume=0
Config_readinInterval=30000
Config_bbCompatibility=0
Config_borderWidth=0
Config_borderPadding=-1
Config_showTaskBar=1
Config_showBorder=0
Config_selBorderColor=
Config_viewNames=1;2;3;4;5
Config_layout_#1=[M];monocle
Config_layout_#2=[]=;tile
Config_layoutCount=2
Config_layoutAxis_#1=1
Config_layoutAxis_#2=2
Config_layoutAxis_#3=2
Config_layoutGapWidth=12
Config_layoutMFactor=0.5
Config_areaTraceTimeout=1000
Config_continuouslyTraceAreas=0
Config_dynamicTiling=1
Config_ghostWndSubString= (Not Responding)
Config_mFactCallInterval=700
Config_mouseFollowsFocus=0
Config_newWndPosition=bottom
Config_onActiveHiddenWnds=view
Config_shellMsgDelay=100
Config_syncMonitorViews=0
Config_viewFollowsTagged=0
Config_viewMargins=0;0;0;0
Config_autoSaveSession=off
Config_maintenanceInterval=5000
Config_monitorDisplayChangeMessages=off
Monitor_#1_aView_#2=2
View_#1_#1_layout_#2=2


; RULES

; Config_rule=a;b;c;d;e;f;g;h;i;j
; a = class
; b = title
; c = function name
; d = is managed
; e = monitor
; f = views / tags
; g = is floating
; h = is decorated
; i = hide title
; j = action on a single window

; DEFAULT RULES:
; Annoying misc hidden background process windows
Config_rule=NarratorHelperWindow;.*;;0;0;0;0;0;0;
Config_rule=WorkerW;;;0;0;0;0;0;0;
Config_rule=Windows\.UI\.Core\.CoreWindow;Feeds;;0;0;0;0;0;0;
Config_rule=WindowsForms10\.Window\.8\.app\.0.*;;;0;0;0;0;0;0;

; SHOW & MANAGE:
; Windows apps
Config_rule=ApplicationFrameWindow;Settings;;1;1;0;0;0;0;
Config_rule=ApplicationFrameWindow;Calculator;;1;1;0;0;0;0;
; TODO: get this to work
Config_rule=ApplicationFrameWindow;Microsoft Store;;1;1;0;0;0;0;
; Notepads (editor)
Config_rule=ApplicationFrameWindow;.*Notepads;;1;1;0;0;0;0;
; Files (file explorer)
Config_rule=ApplicationFrameWindow;.*Files;;1;1;0;0;;;
Config_rule=ApplicationFrameWindow;Properties .*- Files;;0;;;;;;
; Steam - main window
Config_rule=vguiPopupWindow;Steam;;1;1;0;0;0;0;
; Epic Games - launcher
Config_rule=UnrealWindow;Epic Games Launcher;;1;1;0;0;0;0;
; Mod Organizer 2 for Skyrim SE
Config_rule=Qt5152QWindowIcon;.*Mod Organizer.*;;1;1;0;0;0;0;
; X server
Config_rule=vcxsrv.*;.*;;1;1;0;0;0;0;
; Witcher 3 modding tools
Config_rule=Qt5152QWindowIcon;The Witcher 3 Mod Manager;;1;1;0;0;0;0;
Config_rule=WindowsForms10\.Window\.8\.app\.0.*;Script Merger.*;;1;1;0;0;0;0;
Config_rule=WindowsForms10\.Window\.8\.app\.0.*;Wolven kit.*;;1;1;0;0;0;0;

; HIDE & DO NOT MANAGE:
; Creation Kit for Skyrim SE
Config_rule=Creation Kit SE;.*;;0;0;0;0;0;0;
Config_rule=#32770;Object Window;;0;0;0;0;0;0;
Config_rule=#32770;Cell View;;0;0;0;0;0;0;
Config_rule=MonitorClass;Render Window;;0;0;0;0;0;0;
Config_rule=RTEDITLOG;Log;;0;0;0;0;0;0;
; Rocket League - needed?
Config_rule=LaunchUnrealUWindowsClient;Rocket League.*;;0;0;0;0;0;0;
; Control (game)
Config_rule=AppWindowClass;Control .* (FINAL|release);;0;0;0;0;0;0;
; Horizon: Zero Dawn
Config_rule=PIGS_MainWnd;.*;;0;0;0;0;0;0;
; Overwatch 2
Config_rule=TankWindowClass;Overwatch;;0;0;0;0;0;0;
; Dishonored
Config_rule=LaunchUnrealUWindowsClient;Dishonored;;0;0;0;0;0;0;
; OneCommander
Config_rule=HwndWrapper\[OneCommander\.exe.*\];About / Help;;0;0;0;0;0;0;
Config_rule=HwndWrapper\[OneCommander\.exe.*\];One Commander Settings;;0;0;0;0;0;0;
Config_rule=HwndWrapper\[OneCommander\.exe.*\];Extracting .*;;0;0;0;0;0;0;

; CUSTOM RULES:
; Ableton VST windows
Config_rule=AbletonVstPlugClass;.*;;1;0;1;1;1;0;
; Forgot what this is
Config_rule=CASCADIA_HOSTING_WINDOW_CLASS;.*;;1;1;0;0;1;0;
; WSL Xephyr - needed?
Config_rule=RAIL_WINDOW;Xephyr*;;1;1;0;1;0;0;


; HOTKEYS

Config_hotkey=#^+l::Manager_lockWorkStation()
Config_hotkey=#j::View_activateWindow(0, +1)
Config_hotkey=#k::View_activateWindow(0, -1)
Config_hotkey=#+j::View_shuffleWindow(0, +1)
Config_hotkey=#+k::View_shuffleWindow(0, -1)
Config_hotkey=#+Enter::View_shuffleWindow(1)
Config_hotkey=#+q::Manager_closeWindow()
Config_hotkey=#+d::Window_toggleDecor()
Config_hotkey=#s::View_toggleFloatingWindow()
Config_hotkey=#f::Manager_maximizeWindow()
Config_hotkey=#i::Manager_getWindowInfo()
Config_hotkey=#+i::Manager_getWindowList()
Config_hotkey=#Tab::View_setLayout(0, +1)
Config_hotkey=#h::View_setLayoutProperty(MFactor, 0, -0.05)
Config_hotkey=#l::View_setLayoutProperty(MFactor, 0, +0.05)
Config_hotkey=#1::Monitor_activateView(1)
Config_hotkey=#2::Monitor_activateView(2)
Config_hotkey=#3::Monitor_activateView(3)
Config_hotkey=#4::Monitor_activateView(4)
Config_hotkey=#5::Monitor_activateView(5)
Config_hotkey=#+1::Monitor_setWindowTag(1)
Config_hotkey=#+2::Monitor_setWindowTag(2)
Config_hotkey=#+3::Monitor_setWindowTag(3)
Config_hotkey=#+4::Monitor_setWindowTag(4)
Config_hotkey=#+5::Monitor_setWindowTag(5)
Config_hotkey=#^1::Monitor_toggleWindowTag(1)
Config_hotkey=#^2::Monitor_toggleWindowTag(2)
Config_hotkey=#^3::Monitor_toggleWindowTag(3)
Config_hotkey=#^4::Monitor_toggleWindowTag(4)
Config_hotkey=#^5::Monitor_toggleWindowTag(5)
Config_hotkey=#Space::
Config_hotkey=#+Space::Monitor_toggleTaskBar()
Config_hotkey=#+r::Reload
Config_hotkey=#+e::ExitApp
Config_hotkey=#Enter::Run, shell:appsFolder\Microsoft.WindowsTerminal_8wekyb3d8bbwe!App
Config_hotkey=#+Enter::Run, alacritty.exe -e wsl.exe --shell-type login --cd ~
