- name: Bootstrap dotfiles
  hosts: localhost
  connection: local

  tasks:
    # Get package lists
    - name: Get package list
      include_vars:
        file: packages.yaml

    # Ensure pacman packages are installed
    # - name: Ensure pacman packages are installed
    #   become: yes
    #   community.general.pacman:
    #     name: "{{ pacman_pkgs }}"

    # Ensure yay is installed
    - name: Ensure yay is installed
      vars:
        yay_path: "/usr/bin/yay"
      kewlfft.aur.aur:
        name: yay
        use: makepkg
      when: yay_path is not file

    # Ensure aur packages are installed
    - name: Ensure packages are installed
      kewlfft.aur.aur:
        name: "{{ dominus.pkgs }}"
        use: yay

# Deploy symlinks with stow
