# Base16 Hubble - kitty color config
# Scheme by https://github.com/ternishnoddy
background #161616
foreground #d5d5d5
selection_background #d5d5d5
selection_foreground #161616
url_color #cccccc
cursor #d5d5d5
active_border_color #666666
inactive_border_color #222222
active_tab_background #161616
active_tab_foreground #d5d5d5
inactive_tab_background #222222
inactive_tab_foreground #cccccc
tab_bar_background #222222

# normal
color0 #222222
color1 #d23d3d
color2 #379e4d
color3 #fea63c
color4 #66a9b9
color5 #b7416e
color6 #6d878d
color7 #d5d5d5

# bright
color8 #666666
color9 #eb8413
color10 #222222
color11 #444444
color12 #cccccc
color13 #dddddd
color14 #c85e0d
color15 #e5e5e5
