include colors.conf

font_family         FuraCode Nerd Font
bold_font           auto
italic_font         auto
bold_italic_font    auto

font_size 10.0

adjust_line_height  0
adjust_column_width 0

disable_ligature cursor

cursor_shape            block
cursor_blink_interval   0

scrollback_lines 10000

url_style           curly
open_url_modifiers  kitty_mod
url_prefixes        http https file ftp

strip_trailing_spaces       smart
rectangle_select_modifiers  ctrl+alt
terminal_select_modifiers   shift

enable_audio_bell no

window_margin_width     0
window_border_width     1.0
window_padding_width    0
hide_window_decorations yes

clear_all_shortcuts yes
kitty_mod           ctrl+shift

map kitty_mod+c copy_to_clipboard
map kitty_mod+v paste_to_clipboard

map page_up     scroll_page_up
map page_down   scroll_page_down

map kitty_mod+0     change_font_size all 0
map kitty_mod+plus  change_font_size all +0.5
map kitty_mod+minus change_font_size all -0.5
